services:
  mcp_server:
    build: .
    container_name: mcp_aemps
    depends_on:
      - redis
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped

  redis:
    image: redis:8.0-alpine
    container_name: redis_mcp
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --appendonly yes
      --save 900 1
    # No exponemos el puerto al host, solo acceso interno
    # ports:
    #   - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: